### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by kingchenx** [opencryptotrader/arbbot#26]
Hello,
what am i doing wrong? And yes, i have some balance on my wallets, its not empty...
and other question, how i open the webinterface? localhost / not work
thx

13:18:39: Refreshing trading pairs...
13:18:39: Attempting to refresh exchange data before wallets are initialized
13:18:39: Error during main loop: wallets not initialized
#0 /var/www/arbbot-production/Arbitrator.php(410): Bittrex->refreshExchangeData()
#1 /var/www/arbbot-production/Arbitrator.php(38): Arbitrator->refreshCoinPairs()
#2 /var/www/arbbot-production/Arbitrator.php(435): Arbitrator->loop()
#3 /var/www/arbbot-production/main.php(62): Arbitrator->run()
#4 {main}

**Comment by cryptoeax** [comment]
Do you have any balance in either Poloniex or Bittrex?  I think this error suggests that the bot can't find any wallet with an outstanding balance in Bittrex.
